### ISSUE TITLE
xacro releases into ROS2 distros

### ISSUE THREAD

**Issue by rhaschke** [ros2-gbp/xacro-release#1]
Dear @cottsay and @nuclearsandwich,
obviously, when the rolling distro was prepared a while ago, you decided to release xacro here. This is fine, but excludes me, as the maintainer of xacro from releasing xacro myself. I asked for access to this release repo a while ago, but obviously didn't get it yet. So, can someone of you grant me access here to enable updating the ROS releases into rolling and galactic? Thanks a lot in advance.
Best, Robert

**Comment by nuclearsandwich** [comment]
@rhaschke my apologies for the delayed response and thank you for opening the issue.

I've sent you an invite to administer this repository. If you'd like I can also push all ROS 2 related refs from the https://github.com/ros-gbp/xacro-release.git so that this repository can be used to release xacro into all ROS 2 distributions.

**Comment by rhaschke** [comment]
Thanks for granting me access. I will switch to the new ros2-gbp repository for future releases. I think, there is no need to touch that now.
